[25-Jul-2022 20:48:11 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'ErrorException'</p>
<p>Message : 'preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated'</p>
<p>Stack trace: <pre>#0 [internal function]: Core\Error::errorHandler(8192, 'preg_match(): P...', 'C:\\xampp\\htdocs...', 38)
#1 C:\xampp\htdocs\mvcproject\Core\Router.php(38): preg_match('/^\\/?$/i', NULL, NULL)
#2 C:\xampp\htdocs\mvcproject\Core\Router.php(55): Core\Router->match(NULL)
#3 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch(NULL)
#4 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 38</p>

[25-Jul-2022 20:48:11 Europe/Berlin] PHP Fatal error:  Uncaught Exception: ../App/Views/errors/500.php not found in C:\xampp\htdocs\mvcproject\Core\View.php:14
Stack trace:
#0 C:\xampp\htdocs\mvcproject\Core\Error.php(40): Core\View::render('errors/500')
#1 [internal function]: Core\Error::exceptionHandler(Object(ErrorException))
#2 {main}
  thrown in C:\xampp\htdocs\mvcproject\Core\View.php on line 14
[25-Jul-2022 20:48:11 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'Exception'</p>
<p>Message : 'no route matched.'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('favicon.ico')
#1 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 78</p>

[25-Jul-2022 20:48:46 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'ErrorException'</p>
<p>Message : 'preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated'</p>
<p>Stack trace: <pre>#0 [internal function]: Core\Error::errorHandler(8192, 'preg_match(): P...', 'C:\\xampp\\htdocs...', 38)
#1 C:\xampp\htdocs\mvcproject\Core\Router.php(38): preg_match('/^\\/?$/i', NULL, NULL)
#2 C:\xampp\htdocs\mvcproject\Core\Router.php(55): Core\Router->match(NULL)
#3 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch(NULL)
#4 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 38</p>

[25-Jul-2022 20:48:46 Europe/Berlin] PHP Fatal error:  Uncaught Exception: ../App/Views/errors/500.php not found in C:\xampp\htdocs\mvcproject\Core\View.php:14
Stack trace:
#0 C:\xampp\htdocs\mvcproject\Core\Error.php(40): Core\View::render('errors/500')
#1 [internal function]: Core\Error::exceptionHandler(Object(ErrorException))
#2 {main}
  thrown in C:\xampp\htdocs\mvcproject\Core\View.php on line 14
[25-Jul-2022 20:49:41 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'ErrorException'</p>
<p>Message : 'preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated'</p>
<p>Stack trace: <pre>#0 [internal function]: Core\Error::errorHandler(8192, 'preg_match(): P...', 'C:\\xampp\\htdocs...', 38)
#1 C:\xampp\htdocs\mvcproject\Core\Router.php(38): preg_match('/^\\/?$/i', NULL, NULL)
#2 C:\xampp\htdocs\mvcproject\Core\Router.php(55): Core\Router->match(NULL)
#3 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch(NULL)
#4 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 38</p>

[25-Jul-2022 20:49:41 Europe/Berlin] PHP Fatal error:  Uncaught Exception: ../App/Views/errors/500.php not found in C:\xampp\htdocs\mvcproject\Core\View.php:14
Stack trace:
#0 C:\xampp\htdocs\mvcproject\Core\Error.php(40): Core\View::render('errors/500')
#1 [internal function]: Core\Error::exceptionHandler(Object(ErrorException))
#2 {main}
  thrown in C:\xampp\htdocs\mvcproject\Core\View.php on line 14
[25-Jul-2022 20:50:17 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'ErrorException'</p>
<p>Message : 'preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated'</p>
<p>Stack trace: <pre>#0 [internal function]: Core\Error::errorHandler(8192, 'preg_match(): P...', 'C:\\xampp\\htdocs...', 38)
#1 C:\xampp\htdocs\mvcproject\Core\Router.php(38): preg_match('/^\\/?$/i', NULL, NULL)
#2 C:\xampp\htdocs\mvcproject\Core\Router.php(55): Core\Router->match(NULL)
#3 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch(NULL)
#4 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 38</p>

[25-Jul-2022 20:50:17 Europe/Berlin] PHP Fatal error:  Uncaught Exception: ../App/Views/errors/500.php not found in C:\xampp\htdocs\mvcproject\Core\View.php:14
Stack trace:
#0 C:\xampp\htdocs\mvcproject\Core\Error.php(40): Core\View::render('errors/500')
#1 [internal function]: Core\Error::exceptionHandler(Object(ErrorException))
#2 {main}
  thrown in C:\xampp\htdocs\mvcproject\Core\View.php on line 14
[25-Jul-2022 20:50:21 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'ErrorException'</p>
<p>Message : 'preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated'</p>
<p>Stack trace: <pre>#0 [internal function]: Core\Error::errorHandler(8192, 'preg_match(): P...', 'C:\\xampp\\htdocs...', 38)
#1 C:\xampp\htdocs\mvcproject\Core\Router.php(38): preg_match('/^\\/?$/i', NULL, NULL)
#2 C:\xampp\htdocs\mvcproject\Core\Router.php(55): Core\Router->match(NULL)
#3 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch(NULL)
#4 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 38</p>

[25-Jul-2022 20:50:21 Europe/Berlin] PHP Fatal error:  Uncaught Exception: ../App/Views/errors/500.php not found in C:\xampp\htdocs\mvcproject\Core\View.php:14
Stack trace:
#0 C:\xampp\htdocs\mvcproject\Core\Error.php(40): Core\View::render('errors/500')
#1 [internal function]: Core\Error::exceptionHandler(Object(ErrorException))
#2 {main}
  thrown in C:\xampp\htdocs\mvcproject\Core\View.php on line 14
[25-Jul-2022 21:13:34 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'Exception'</p>
<p>Message : 'no route matched.'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('auth/login.php')
#1 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 78</p>

[25-Jul-2022 21:15:11 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'Exception'</p>
<p>Message : 'no route matched.'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('auth/login.php')
#1 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 78</p>

[25-Jul-2022 21:16:53 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'Exception'</p>
<p>Message : 'no route matched.'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('auth/login.php')
#1 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 78</p>

[25-Jul-2022 21:21:14 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'Exception'</p>
<p>Message : 'no route matched.'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('auth/login.php')
#1 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 78</p>

[25-Jul-2022 21:22:25 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'Exception'</p>
<p>Message : 'no route matched.'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('auth/login.php')
#1 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 78</p>

[25-Jul-2022 21:22:30 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'Exception'</p>
<p>Message : 'no route matched.'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('auth/login.php')
#1 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 78</p>

[25-Jul-2022 21:25:46 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'Error'</p>
<p>Message : 'Class "App\Models\User" not found'</p>
<p>Stack trace: <pre>#0 [internal function]: App\Controllers\HomeController->index()
#1 C:\xampp\htdocs\mvcproject\Core\Router.php(67): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('')
#3 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\App\Controllers\HomeController.php' on line 12</p>

[25-Jul-2022 21:25:46 Europe/Berlin] PHP Fatal error:  Uncaught Exception: ../App/Views/errors/500.php not found in C:\xampp\htdocs\mvcproject\Core\View.php:14
Stack trace:
#0 C:\xampp\htdocs\mvcproject\Core\Error.php(40): Core\View::render('errors/500')
#1 [internal function]: Core\Error::exceptionHandler(Object(Error))
#2 {main}
  thrown in C:\xampp\htdocs\mvcproject\Core\View.php on line 14
[25-Jul-2022 21:28:16 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'Error'</p>
<p>Message : 'Class "App\Models\User" not found'</p>
<p>Stack trace: <pre>#0 [internal function]: App\Controllers\HomeController->index()
#1 C:\xampp\htdocs\mvcproject\Core\Router.php(67): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('')
#3 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\App\Controllers\HomeController.php' on line 12</p>

[25-Jul-2022 21:28:16 Europe/Berlin] PHP Fatal error:  Uncaught Exception: ../App/Views/errors/500.php not found in C:\xampp\htdocs\mvcproject\Core\View.php:14
Stack trace:
#0 C:\xampp\htdocs\mvcproject\Core\Error.php(40): Core\View::render('errors/500')
#1 [internal function]: Core\Error::exceptionHandler(Object(Error))
#2 {main}
  thrown in C:\xampp\htdocs\mvcproject\Core\View.php on line 14
[25-Jul-2022 21:28:17 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'Error'</p>
<p>Message : 'Class "App\Models\User" not found'</p>
<p>Stack trace: <pre>#0 [internal function]: App\Controllers\HomeController->index()
#1 C:\xampp\htdocs\mvcproject\Core\Router.php(67): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('')
#3 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\App\Controllers\HomeController.php' on line 12</p>

[25-Jul-2022 21:28:17 Europe/Berlin] PHP Fatal error:  Uncaught Exception: ../App/Views/errors/500.php not found in C:\xampp\htdocs\mvcproject\Core\View.php:14
Stack trace:
#0 C:\xampp\htdocs\mvcproject\Core\Error.php(40): Core\View::render('errors/500')
#1 [internal function]: Core\Error::exceptionHandler(Object(Error))
#2 {main}
  thrown in C:\xampp\htdocs\mvcproject\Core\View.php on line 14
[25-Jul-2022 21:28:22 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'Error'</p>
<p>Message : 'Class "App\Models\User" not found'</p>
<p>Stack trace: <pre>#0 [internal function]: App\Controllers\HomeController->index()
#1 C:\xampp\htdocs\mvcproject\Core\Router.php(67): call_user_func_array(Array, Array)
#2 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('')
#3 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\App\Controllers\HomeController.php' on line 12</p>

[25-Jul-2022 21:28:22 Europe/Berlin] PHP Fatal error:  Uncaught Exception: ../App/Views/errors/500.php not found in C:\xampp\htdocs\mvcproject\Core\View.php:14
Stack trace:
#0 C:\xampp\htdocs\mvcproject\Core\Error.php(40): Core\View::render('errors/500')
#1 [internal function]: Core\Error::exceptionHandler(Object(Error))
#2 {main}
  thrown in C:\xampp\htdocs\mvcproject\Core\View.php on line 14
[25-Jul-2022 21:31:31 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'ParseError'</p>
<p>Message : 'syntax error, unexpected token "echo", expecting "function" or "const"'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\vendor\composer\ClassLoader.php(301): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\mvcproject\App\Controllers\HomeController.php(11): Composer\Autoload\ClassLoader->loadClass('App\\Models\\User')
#2 [internal function]: App\Controllers\HomeController->index()
#3 C:\xampp\htdocs\mvcproject\Core\Router.php(67): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('')
#5 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\App\Models\User.php' on line 10</p>

[25-Jul-2022 21:31:31 Europe/Berlin] PHP Fatal error:  Uncaught Exception: ../App/Views/errors/500.php not found in C:\xampp\htdocs\mvcproject\Core\View.php:14
Stack trace:
#0 C:\xampp\htdocs\mvcproject\Core\Error.php(40): Core\View::render('errors/500')
#1 [internal function]: Core\Error::exceptionHandler(Object(ParseError))
#2 {main}
  thrown in C:\xampp\htdocs\mvcproject\Core\View.php on line 14
[25-Jul-2022 21:33:31 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'ParseError'</p>
<p>Message : 'syntax error, unexpected identifier "var_dump", expecting "function" or "const"'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\vendor\composer\ClassLoader.php(301): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\mvcproject\App\Controllers\HomeController.php(11): Composer\Autoload\ClassLoader->loadClass('App\\Models\\User')
#2 [internal function]: App\Controllers\HomeController->index()
#3 C:\xampp\htdocs\mvcproject\Core\Router.php(67): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('')
#5 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\App\Models\User.php' on line 8</p>

[25-Jul-2022 21:33:31 Europe/Berlin] PHP Fatal error:  Uncaught Exception: ../App/Views/errors/500.php not found in C:\xampp\htdocs\mvcproject\Core\View.php:14
Stack trace:
#0 C:\xampp\htdocs\mvcproject\Core\Error.php(40): Core\View::render('errors/500')
#1 [internal function]: Core\Error::exceptionHandler(Object(ParseError))
#2 {main}
  thrown in C:\xampp\htdocs\mvcproject\Core\View.php on line 14
[25-Jul-2022 21:33:31 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'ParseError'</p>
<p>Message : 'syntax error, unexpected identifier "var_dump", expecting "function" or "const"'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\vendor\composer\ClassLoader.php(301): Composer\Autoload\includeFile('C:\\xampp\\htdocs...')
#1 C:\xampp\htdocs\mvcproject\App\Controllers\HomeController.php(11): Composer\Autoload\ClassLoader->loadClass('App\\Models\\User')
#2 [internal function]: App\Controllers\HomeController->index()
#3 C:\xampp\htdocs\mvcproject\Core\Router.php(67): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('')
#5 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\App\Models\User.php' on line 8</p>

[25-Jul-2022 21:33:31 Europe/Berlin] PHP Fatal error:  Uncaught Exception: ../App/Views/errors/500.php not found in C:\xampp\htdocs\mvcproject\Core\View.php:14
Stack trace:
#0 C:\xampp\htdocs\mvcproject\Core\Error.php(40): Core\View::render('errors/500')
#1 [internal function]: Core\Error::exceptionHandler(Object(ParseError))
#2 {main}
  thrown in C:\xampp\htdocs\mvcproject\Core\View.php on line 14
[25-Jul-2022 21:58:25 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'Exception'</p>
<p>Message : 'no route matched.'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('auth/login.php')
#1 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 78</p>

[25-Jul-2022 21:58:31 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'Exception'</p>
<p>Message : 'no route matched.'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('auth/login.php')
#1 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 78</p>

[25-Jul-2022 21:59:09 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'Exception'</p>
<p>Message : 'no route matched.'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('auth/login.php')
#1 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 78</p>

[25-Jul-2022 22:00:07 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'Exception'</p>
<p>Message : 'no route matched.'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('auth/login.php')
#1 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 78</p>

[25-Jul-2022 22:03:32 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'Exception'</p>
<p>Message : 'no route matched.'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('App/Views/index...')
#1 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 78</p>

[25-Jul-2022 22:04:10 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'Exception'</p>
<p>Message : 'no route matched.'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('App/Views/index...')
#1 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 78</p>

[25-Jul-2022 22:04:20 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'Exception'</p>
<p>Message : 'no route matched.'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('App/Views/index...')
#1 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 78</p>

[25-Jul-2022 22:06:18 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'Exception'</p>
<p>Message : 'no route matched.'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('mvcproject.test')
#1 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 78</p>

[25-Jul-2022 22:06:34 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'Exception'</p>
<p>Message : 'no route matched.'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('mvcproject.test')
#1 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 78</p>

[25-Jul-2022 23:10:23 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'ParseError'</p>
<p>Message : 'Unclosed '{' on line 18'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\App\Controllers\HomeController.php(14): Core\View::render('index')
#1 [internal function]: App\Controllers\HomeController->index()
#2 C:\xampp\htdocs\mvcproject\Core\Router.php(67): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('')
#4 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\App\Views\index.php' on line 95</p>

[25-Jul-2022 23:10:23 Europe/Berlin] PHP Fatal error:  Uncaught Exception: ../App/Views/errors/500.php not found in C:\xampp\htdocs\mvcproject\Core\View.php:14
Stack trace:
#0 C:\xampp\htdocs\mvcproject\Core\Error.php(40): Core\View::render('errors/500')
#1 [internal function]: Core\Error::exceptionHandler(Object(ParseError))
#2 {main}
  thrown in C:\xampp\htdocs\mvcproject\Core\View.php on line 14
[25-Jul-2022 23:10:30 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'ParseError'</p>
<p>Message : 'Unclosed '{' on line 18'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\App\Controllers\HomeController.php(14): Core\View::render('index')
#1 [internal function]: App\Controllers\HomeController->index()
#2 C:\xampp\htdocs\mvcproject\Core\Router.php(67): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('')
#4 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\App\Views\index.php' on line 95</p>

[25-Jul-2022 23:10:30 Europe/Berlin] PHP Fatal error:  Uncaught Exception: ../App/Views/errors/500.php not found in C:\xampp\htdocs\mvcproject\Core\View.php:14
Stack trace:
#0 C:\xampp\htdocs\mvcproject\Core\Error.php(40): Core\View::render('errors/500')
#1 [internal function]: Core\Error::exceptionHandler(Object(ParseError))
#2 {main}
  thrown in C:\xampp\htdocs\mvcproject\Core\View.php on line 14
[25-Jul-2022 23:41:27 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'Exception'</p>
<p>Message : 'no route matched.'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('mvcproject.test...')
#1 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\Core\Router.php' on line 78</p>

[25-Jul-2022 23:43:46 Europe/Berlin] 
<h1>Fatal error</h1>
<p>Uncaught exception: 'ErrorException'</p>
<p>Message : 'require_once(./../error_message.php): Failed to open stream: No such file or directory'</p>
<p>Stack trace: <pre>#0 C:\xampp\htdocs\mvcproject\App\Views\register.php(2): Core\Error::errorHandler(2, 'require_once(./...', 'C:\\xampp\\htdocs...', 2)
#1 C:\xampp\htdocs\mvcproject\App\Views\register.php(2): require_once()
#2 C:\xampp\htdocs\mvcproject\Core\View.php(12): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\mvcproject\App\Controllers\SeriesController.php(14): Core\View::render('register')
#4 [internal function]: App\Controllers\SeriesController->register()
#5 C:\xampp\htdocs\mvcproject\Core\Router.php(67): call_user_func_array(Array, Array)
#6 C:\xampp\htdocs\mvcproject\public\index.php(10): Core\Router->dispatch('register')
#7 {main}</pre></p>
<p>Thrown in 'C:\xampp\htdocs\mvcproject\App\Views\register.php' on line 2</p>

[25-Jul-2022 23:43:46 Europe/Berlin] PHP Fatal error:  Uncaught Exception: ../App/Views/errors/500.php not found in C:\xampp\htdocs\mvcproject\Core\View.php:14
Stack trace:
#0 C:\xampp\htdocs\mvcproject\Core\Error.php(40): Core\View::render('errors/500')
#1 [internal function]: Core\Error::exceptionHandler(Object(ErrorException))
#2 {main}
  thrown in C:\xampp\htdocs\mvcproject\Core\View.php on line 14
